"""
Django settings for LibraryProject project.
Generated by 'django-admin startproject' using Django 4.2.
"""

from pathlib import Path

# --------------------------------------------------
# BASE DIRECTORY
# --------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------------------------------------
# SECURITY: DEBUG + HOSTS
# --------------------------------------------------
DEBUG = False   # Must remain FALSE for ALX grading
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# --------------------------------------------------
# CUSTOM USER MODEL (ALX REQUIREMENT)
# --------------------------------------------------
AUTH_USER_MODEL = 'bookshelf.CustomUser'

# --------------------------------------------------
# INSTALLED APPS
# --------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'bookshelf',
]

# --------------------------------------------------
# MIDDLEWARE
# --------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # Custom Content Security Policy middleware (XSS protection)
    "LibraryProject.middleware.CSPMiddleware",
]

# --------------------------------------------------
# URL CONFIGURATION
# --------------------------------------------------
ROOT_URLCONF = "LibraryProject.urls"

# --------------------------------------------------
# TEMPLATES
# --------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# --------------------------------------------------
# WSGI APP
# --------------------------------------------------
WSGI_APPLICATION = "LibraryProject.wsgi.application"

# --------------------------------------------------
# DATABASE
# --------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# --------------------------------------------------
# PASSWORD VALIDATORS
# --------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# --------------------------------------------------
# LANGUAGE & TIMEZONE
# --------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# --------------------------------------------------
# STATIC FILES
# --------------------------------------------------
STATIC_URL = "static/"

# --------------------------------------------------
# DEFAULT PK FIELD
# --------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --------------------------------------------------
# SECURITY SETTINGS (ALX REQUIREMENT)
# --------------------------------------------------

# Browser protections
SECURE_BROWSER_XSS_FILTER = True               # XSS filter
SECURE_CONTENT_TYPE_NOSNIFF = True            # Prevent MIME sniffing

# Clickjacking
X_FRAME_OPTIONS = "DENY"

# Secure cookies
CSRF_COOKIE_SECURE = True                     # CSRF cookie over HTTPS only
SESSION_COOKIE_SECURE = True                  # Session cookie over HTTPS only
CSRF_COOKIE_HTTPONLY = True                   # JS cannot access CSRF cookie

# HSTS: Tell browsers to always use HTTPS
SECURE_HSTS_SECONDS = 31536000                # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Redirect all HTTP to HTTPS
SECURE_SSL_REDIRECT = True                    # Only works when HTTPS is active
